from html import escape
from pathlib import Path


def write_html_report(config_name, findings, output_path):
    output_path = Path(output_path)

    counts = {
        "High": sum(1 for f in findings if f["severity"] == "High"),
        "Medium": sum(1 for f in findings if f["severity"] == "Medium"),
        "Low": sum(1 for f in findings if f["severity"] == "Low"),
    }

    rows = []
    for item in findings:
        rows.append(
            f"""
            <tr>
                <td>{escape(item['rule_id'])}</td>
                <td><strong>{escape(item['title'])}</strong></td>
                <td>{escape(item['severity'])}</td>
                <td><code>{escape(item['evidence'])}</code></td>
                <td>{escape(item['explanation'])}</td>
                <td>{escape(item['recommendation'])}</td>
            </tr>
            """
        )

    if not rows:
        rows.append(
            """
            <tr>
                <td colspan="6">No findings were generated by the current rule set.</td>
            </tr>
            """
        )

    html = f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cisco Configuration Audit Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 32px;
            line-height: 1.45;
            color: #222;
        }}
        h1 {{ margin-bottom: 4px; }}
        .meta {{ color: #666; margin-bottom: 24px; }}
        .summary {{
            display: flex;
            gap: 16px;
            margin: 20px 0;
            flex-wrap: wrap;
        }}
        .card {{
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 12px 18px;
            min-width: 110px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
            vertical-align: top;
        }}
        th {{ background: #f4f4f4; }}
        code {{
            white-space: pre-wrap;
            word-break: break-word;
        }}
    </style>
</head>
<body>
    <h1>Cisco Configuration Audit Report</h1>
    <div class="meta">Source configuration: {escape(config_name)}</div>

    <div class="summary">
        <div class="card"><strong>Total</strong><br>{len(findings)}</div>
        <div class="card"><strong>High</strong><br>{counts['High']}</div>
        <div class="card"><strong>Medium</strong><br>{counts['Medium']}</div>
        <div class="card"><strong>Low</strong><br>{counts['Low']}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Rule</th>
                <th>Finding</th>
                <th>Severity</th>
                <th>Evidence</th>
                <th>Why it matters</th>
                <th>Recommendation</th>
            </tr>
        </thead>
        <tbody>
            {''.join(rows)}
        </tbody>
    </table>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")
    return output_path.resolve()
